# Generated by Django 5.0.3 on 2024-05-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_prettynum_alter_userinfo_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='crt_time',
            field=models.DateField(verbose_name='入职时间'),
        ),
    ]
